<# .SYNOPSIS
PLAN.md 의 모든 레벨·주제에 대해 입문자용 가이드(Summary + Example)를
자동으로 채워서 Markdown 파일로 생성합니다.
LLM API 키가 없어도 즉시 실행 가능합니다.
#>

function New-GuideFile {
    param(
        [string]$BaseDir,
        [int]$Level,
        [string]$Topic,
        [string]$Official,
        [string]$Url,
        [string]$Lang   # "Python" 또는 "Java"
    )
    $levelFolder = "{0:D2}" -f $Level                 # 01, 02 …
    $targetDir = Join-Path $BaseDir $levelFolder
    if (-not (Test-Path $targetDir)) {
        New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    }

    $safeTopic = $Topic -replace '[\\/:*?"<>|]', '' -replace '\s+', '_'   # 파일명 안전화
    $filePath = Join-Path $targetDir "$safeTopic.md"

    # ---- 요약 / 예시 자동 생성 (LLM 없이도 즉시 사용 가능) ----
    $summary = "이 섹션은 **$Topic** 의 핵심 개념과 대표 사용 사례를 소개합니다."
    if ($Lang -eq "Python") {
        $example = "print('Example of $Topic')"
    } else { # Java
        $example = 'System.out.println("Example of ' + $Topic + '");'
    }

    $content = @"
# $Topic

## Official Documentation
- [$Official]($Url)

## Summary
> $summary

## Example
```$($Lang.ToLower())
$example
```

---
Generated by fill-all-guides.ps1
"@

    Set-Content -Path $filePath -Value $content -Encoding UTF8
    Write-Host "Created: $filePath"
}

# -------------------------------------------------
# Spring Boot (Java)  →  docs/01.SpringBoot3.4.x/
# -------------------------------------------------
$springPlan = "docs/01.SpringBoot3.4.x/PLAN.md"
$lines = Get-Content $springPlan -Encoding UTF8
$startIdx = -1
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '^\s*\|\s*Level') { $startIdx = $i; break }
}
if ($startIdx -ge 0) {
    for ($i = $startIdx + 2; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -notmatch '^\s*\|') { break }
        $cols = $line.Trim('|') -split '\s*\|\s*'
        $levelStr = $cols[0].Trim()
        if (-not ($levelStr -match '^\d+$')) { continue }
        $level   = [int]$levelStr
        $topic   = $cols[1].Trim()
        $official= $cols[2].Trim()
        $url     = $cols[3].Trim()
        New-GuideFile -BaseDir "docs/01.SpringBoot3.4.x" `
                      -Level $level -Topic $topic -Official $official -Url $url -Lang "Java"
    }
}

# -------------------------------------------------
# Python 3.12  →  docs/02.Python3.12/
# -------------------------------------------------
$pythonPlan = "docs/02.Python3.12/PLAN.md"
$lines = Get-Content $pythonPlan -Encoding UTF8
$startIdx = -1
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '^\s*\|\s*Level') { $startIdx = $i; break }
}
if ($startIdx -ge 0) {
    for ($i = $startIdx + 2; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -notmatch '^\s*\|') { break }
        $cols = $line.Trim('|') -split '\s*\|\s*'
        $levelStr = $cols[0].Trim()
        if (-not ($levelStr -match '^\d+$')) { continue }
        $level   = [int]$levelStr
        $topic   = $cols[1].Trim()
        $official= $cols[2].Trim()
        $url     = $cols[3].Trim()
        New-GuideFile -BaseDir "docs/02.Python3.12" `
                      -Level $level -Topic $topic -Official $official -Url $url -Lang "Python"
    }
}