<# .SYNOPSIS
Generate per-section markdown guides from PLAN.md tables.
#>
function New-GuideFile {
    param(
        [string]$BaseDir,
        [int]$Level,
        [string]$Topic,
        [string]$Official,
        [string]$Url
    )
    $levelFolder = "{0:D2}" -f $Level
    Write-Host "Processing Level=$Level folder=$levelFolder"
    $targetDir = Join-Path $BaseDir $levelFolder
    if (-not (Test-Path $targetDir)) { Write-Host "Creating folder: $targetDir"; New-Item -ItemType Directory -Path $targetDir -Force | Out-Null }
    $safeTopic = $Topic -replace '[\\/:*?"<>|]', '' -replace '\\s+', '_' 
    $filePath = Join-Path $targetDir "$safeTopic.md"
    $content = @"
# $Topic

## Official Documentation
- [$Official]($Url)

## Summary
> Add a brief summary here.

## Example
```
# Write example code here
```

---
Generated by generate-topic-guides.ps1
"@ 
    Set-Content -Path $filePath -Value $content -Encoding UTF8
    Write-Host "Created: $filePath"
}
# Process Spring Boot PLAN
$springPlan = "docs/01.SpringBoot3.4.x/PLAN.md"
$lines = Get-Content $springPlan -Encoding UTF8
$startIdx = -1
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '^\s*\|\s*Level') { $startIdx = $i; break }
}
Write-Host "Spring startIdx=$startIdx"
if ($startIdx -ge 0) {
    for ($i = $startIdx + 2; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -notmatch '^\s*\|') { break }
        $cols = $line.Trim('|') -split '\s*\|\s*'
        $levelStr = $cols[1].Trim()
        if (-not ($levelStr -match '^\\d+$')) { continue }
        $level = [int]$levelStr
        $topic = $cols[2].Trim()
        $official = $cols[3].Trim()
        $url = $cols[4].Trim()
        Write-Host "Spring processing Level=$level Topic=$topic"
        New-GuideFile -BaseDir "docs/01.SpringBoot3.4.x" -Level $level -Topic $topic -Official $official -Url $url
    }
}
# Process Python PLAN
$pythonPlan = "docs/02.Python3.12/PLAN.md"
$lines = Get-Content $pythonPlan -Encoding UTF8
$startIdx = -1
for ($i = 0; $i -lt $lines.Count; $i++) {
    if ($lines[$i] -match '^\s*\|\s*Level') { $startIdx = $i; break }
}
Write-Host "Python startIdx=$startIdx"
if ($startIdx -ge 0) {
    for ($i = $startIdx + 2; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -notmatch '^\s*\|') { break }
        $cols = $line.Trim('|') -split '\s*\|\s*'
        $levelStr = $cols[1].Trim()
        if (-not ($levelStr -match '^\\d+$')) { continue }
        $level = [int]$levelStr
        $topic = $cols[3].Trim()
        $official = $topic
        $url = $cols[4].Trim()
        Write-Host "Python processing Level=$level Topic=$topic"
        New-GuideFile -BaseDir "docs/02.Python3.12" -Level $level -Topic $topic -Official $official -Url $url
    }
}
