<# .SYNOPSIS
Generate per-section markdown guides from PLAN.md tables.
#>
function New-GuideFile {
    param(
        [string]$BaseDir,
        [int]$Level,
        [string]$Topic,
        [string]$Official,
        [string]$Url
    )
    $levelFolder = "{0:D2}" -f $Level
    $targetDir = Join-Path $BaseDir $levelFolder
    if (-not (Test-Path $targetDir)) { New-Item -ItemType Directory -Path $targetDir | Out-Null }
    $safeTopic = $Topic -replace '[\\/:*?"<>|]', '' -replace '\\s+', '_' 
    $filePath = Join-Path $targetDir "$safeTopic.md"
    $content = @(
        "# $Topic",
        "",
        "## Official Documentation",
        "- [$Official]($Url)",
        "",
        "## Summary",
        "> Add a brief summary here.",
        "",
        "## Example",
        "```",
        "# Write example code here",
        "```",
        "",
        "---",
        "*Generated by generate-topic-guides.ps1*"
    ) -join "`n"
    Set-Content -Path $filePath -Value $content -Encoding UTF8
    Write-Host "Created: $filePath"
}
# Process Spring Boot PLAN
$springPlan = "docs/01.SpringBoot3.4.x/PLAN.md"
$lines = Get-Content $springPlan -Encoding UTF8
$startIdx = $lines.FindIndex({$_ -match '^\\| *Level'})
if ($startIdx -ge 0) {
    for ($i = $startIdx + 2; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -notmatch '^\\|') { break }
        $cols = $line -split '\\|'
        $level = [int]($cols[1].Trim())
        $topic = $cols[2].Trim()
        $official = $cols[3].Trim()
        $url = $cols[4].Trim()
        New-GuideFile -BaseDir "docs/01.SpringBoot3.4.x" -Level $level -Topic $topic -Official $official -Url $url
    }
}
# Process Python PLAN
$pythonPlan = "docs/02.Python3.12/PLAN.md"
$lines = Get-Content $pythonPlan -Encoding UTF8
$startIdx = $lines.FindIndex({$_ -match '^\\| *Level'})
if ($startIdx -ge 0) {
    for ($i = $startIdx + 2; $i -lt $lines.Count; $i++) {
        $line = $lines[$i]
        if ($line -notmatch '^\\|') { break }
        $cols = $line -split '\\|'
        $levelStr = $cols[1].Trim()
        if ($levelStr -match '^(\\d+)') { $level = [int]$matches[1] } else { continue }
        $topic = $cols[3].Trim()
        $official = $topic
        $url = $cols[4].Trim()
        New-GuideFile -BaseDir "docs/02.Python3.12" -Level $level -Topic $topic -Official $official -Url $url
    }
}
